In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('/Users/aryam/Downloads/2.12_Health_systems.csv')

In [3]:
df

,Country_Region,Province_State,World_Bank_Name,Health_exp_pct_GDP_2016,Health_exp_public_pct_2016,Health_exp_out_of_pocket_pct_2016,Health_exp_per_capita_USD_2016,per_capita_exp_PPP_2016,External_health_exp_pct_2016,Physicians_per_1000_2009-18,Nurse_midwife_per_1000_2009-18,Specialist_surgical_per_1000_2008-18,Completeness_of_birth_reg_2009-18,Completeness_of_death_reg_2008-16
0,Afghanistan,NaN,Afghanistan,10.2,5.1,77.4,57.2,162.8,17.5,0.3,0.3,0.0,42.3,NaN
1,Albania,NaN,Albania,6.7,41.4,58.0,271.5,759.7,0.7,1.2,3.6,11.6,98.4,53.0
2,Algeria,NaN,Algeria,6.6,67.7,30.9,260.4,998.2,0.0,1.8,2.2,12.1,100.0,NaN
3,Andorra,NaN,Andorra,10.4,49.1,41.7,3834.7,4978.7,NaN,3.3,4.0,83.1,100.0,80.0
4,Angola,NaN,Angola,2.9,44.1,35.2,95.2,185.8,3.6,0.2,1.3,NaN,25.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
205,US,Virgin Islands,Virgin Islands (U.S.),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
206,NaN,NaN,West Bank and Gaza,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,96.0,NaN
207,NaN,NaN,"Yemen, Rep.",5.6,10.2,81.0,72.0,144.5,7.8,0.3,0.7,0.8,30.7,NaN
208,Zambia,NaN,Zambia,4.5,38.3,12.1,56.5,175.2,42.5,0.1,0.9,1.5,11.3,NaN
209,Zimbabwe,NaN,Zimbabwe,9.4,46.5,21.2,93.9,185.0,25.4,0.1,1.2,1.6,38.0,NaN

In [4]:
df.isnull().sum()

Country_Region                           23
Province_State                          196
World_Bank_Name                           0
Health_exp_pct_GDP_2016                  24
Health_exp_public_pct_2016               24
Health_exp_out_of_pocket_pct_2016        24
Health_exp_per_capita_USD_2016           24
per_capita_exp_PPP_2016                  24
External_health_exp_pct_2016             43
Physicians_per_1000_2009-18              21
Nurse_midwife_per_1000_2009-18           21
Specialist_surgical_per_1000_2008-18     35
Completeness_of_birth_reg_2009-18        47
Completeness_of_death_reg_2008-16       103
dtype: int64

In [5]:
df.describe()

,Health_exp_pct_GDP_2016,Health_exp_public_pct_2016,Health_exp_out_of_pocket_pct_2016,Health_exp_per_capita_USD_2016,per_capita_exp_PPP_2016,External_health_exp_pct_2016,Physicians_per_1000_2009-18,Nurse_midwife_per_1000_2009-18,Specialist_surgical_per_1000_2008-18,Completeness_of_birth_reg_2009-18,Completeness_of_death_reg_2008-16
count,186.000000,186.000000,186.000000,186.000000,186.000000,167.000000,189.000000,189.000000,175.000000,163.000000,107.000000
mean,6.715054,52.915054,32.661828,1037.004839,1412.466667,9.116766,1.723280,4.139153,37.937143,84.202454,89.309346
std,2.976537,21.957736,19.572777,1712.592621,1690.018939,13.868251,1.570366,3.965282,40.877520,23.370024,18.071157
min,1.700000,5.100000,0.100000,16.400000,29.900000,0.000000,0.000000,0.100000,0.000000,2.700000,4.000000
25%,4.500000,36.825000,16.200000,85.700000,231.500000,0.200000,0.300000,1.100000,3.100000,77.150000,85.500000
50%,6.200000,55.850000,30.100000,322.600000,782.500000,1.700000,1.300000,2.800000,23.600000,96.000000,99.000000
75%,8.375000,70.600000,44.825000,1059.800000,1885.500000,13.400000,2.800000,6.100000,62.150000,100.000000,100.000000
max,23.300000,96.000000,81.000000,9869.700000,9869.700000,69.200000,8.200000,20.300000,195.600000,100.000000,100.000000

In [15]:
df = df['Completeness_of_death_reg_2008-16'].replace('NaN', 89.309346, inplace=True)